In [ ]:
import numpy as np
import random


###Уровень 0:
####Задание 1

   * Создайте матрицу 3 на 3, заполненную числами от 1 до 9
   * Прибавьте к ней матрицу с единицами на диагонале
   * Умножьте полученную матрицу на вектор (1, 2, 3)
   * Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
   * Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
A = np.arange(1, 10) # создаем массив от 1 до 9
random.shuffle(A) # перемешиваем случайно числа
A = A.reshape(3, 3) # изменяем размерность, получаем матрицу 3х3
A

array([[2, 7, 3],
       [1, 4, 6],
       [9, 8, 5]])

In [ ]:
B = np.eye(3) # диагональная единичная матрица
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
C = A + B
C

array([[3., 7., 3.],
       [1., 5., 6.],
       [9., 8., 6.]])

In [ ]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [ ]:
np.dot(C, v) # умножение матрицы на столбец

array([26., 29., 43.])

In [ ]:
np.transpose(C) # транспонирование матрицы С

array([[3., 1., 9.],
       [7., 5., 8.],
       [3., 6., 6.]])

In [ ]:
np.linalg.inv(C) # обратная матрица для матрицы С

array([[-0.10526316, -0.10526316,  0.15789474],
       [ 0.28070175, -0.05263158, -0.0877193 ],
       [-0.21637427,  0.22807018,  0.04678363]])


###Уровень 1:
####Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)



In [ ]:
m = np.array([[2, 2], [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
np.linalg.eig(m) # собственные значения и вектора

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))


####Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!


In [ ]:
M = np.array([[2, 1], [5, 3]])
np.linalg.det(M)

1.0000000000000009